version: '3.8'

services:

  postgres:
    image: postgis/postgis:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: test
    ports: 
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  influxdb:
    image: influxdb:latest
    restart: unless-stopped
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  chronograf:
    image: chronograf:latest
    restart: unless-stopped
    ports:
      - '127.0.0.1:8888:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_BUCKET=mydb
      - DOCKER_INFLUXDB_INIT_ORG=G15
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=rKZqxHPu306Yrt1sJkPH2zcFY7VoH3t34B40xLnPhisQZty-yokN-kqcTzMJBm6xTbPmbPwExB1obFvUEYCKXw==
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
  

volumes:
  pgdata:
  influxdb-storage:
  chronograf-storage:
  grafana-storage:
      